// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/tachi_landing_page/PlasmicGlobalContextsProvider";

import { PlasmicOnboarding } from "../components/plasmic/tachi_landing_page/PlasmicOnboarding";
import { useRouter } from "next/router";

function Onboarding() {
  // Use PlasmicOnboarding to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.

  return (
    <GlobalContextsProvider>
      <PageParamsProvider__
        route={useRouter()?.pathname}
        params={useRouter()?.query}
        query={useRouter()?.query}
      >
        <PlasmicOnboarding />
      </PageParamsProvider__>
    </GlobalContextsProvider>
  );
}

export default Onboarding;
