name = "tachi-gateway"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Workers.dev subdomain (will be: tachi-gateway.your-subdomain.workers.dev)
workers_dev = true

[env.production]
name = "tachi-gateway-production"
vars = {ENVIRONMENT = "production"}

# Environment variables (set via wrangler secret put)
# SUPABASE_URL
# SUPABASE_KEY
# BASE_RPC_URL
# CRAWL_NFT_ADDRESS
# PROOF_OF_CRAWL_ADDRESS
# PRICE_PER_REQUEST (in USDC, e.g., "0.01")
# PUBLISHER_ADDRESS
