/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: buLarKS5F8q92wwXeZGLFH

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsbgbUyiOiPp2W } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: bgbUyiOIPp2W/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsbgbUyiOiPp2W
});
