/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: buLarKS5F8q92wwXeZGLFH
// Component: bsb7KzqnDfzt

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: 8HcwSFor26rJ/component
import OCard from "../../OCard"; // plasmic-import: fweFoRIjeuAZ/component
import TextField from "../../TextField"; // plasmic-import: R_nijpoBPDhQ/component
import CheckboxGroup from "../../CheckboxGroup"; // plasmic-import: zZwKqXzF3N9z/component
import Checkbox from "../../Checkbox"; // plasmic-import: mEbWDJNOPQTG/component
import Button from "../../Button"; // plasmic-import: QX58X5UGGXHk/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: buLarKS5F8q92wwXeZGLFH/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: buLarKS5F8q92wwXeZGLFH/styleTokensProvider
import { _useStyleTokens as useStyleTokens_library_plasmic_color_type } from "../library_plasmic_color_type/PlasmicStyleTokensProvider"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: buLarKS5F8q92wwXeZGLFH/projectcss
import sty from "./PlasmicOnboarding4.module.css"; // plasmic-import: bsb7KzqnDfzt/css

import ProggressingAnimationIcon from "./icons/PlasmicIcon__ProggressingAnimation"; // plasmic-import: VjJuArAbReif/icon
import TickCircleIcon from "./icons/PlasmicIcon__TickCircle"; // plasmic-import: BBx1XSheLP80/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: ZNonLQPDz_Kq/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: tipwXQCWEsbd/icon

createPlasmicElementProxy;

export type PlasmicOnboarding4__VariantMembers = {};
export type PlasmicOnboarding4__VariantsArgs = {};
type VariantPropType = keyof PlasmicOnboarding4__VariantsArgs;
export const PlasmicOnboarding4__VariantProps = new Array<VariantPropType>();

export type PlasmicOnboarding4__ArgsType = {};
type ArgPropType = keyof PlasmicOnboarding4__ArgsType;
export const PlasmicOnboarding4__ArgProps = new Array<ArgPropType>();

export type PlasmicOnboarding4__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  section?: Flex__<"section">;
  columns?: Flex__<"div">;
  icons3?: Flex__<"div">;
  line1?: Flex__<"div">;
  icons8?: Flex__<"div">;
  icons9?: Flex__<"div">;
  icons10?: Flex__<"div">;
  icons11?: Flex__<"div">;
  icons12?: Flex__<"div">;
  icons13?: Flex__<"div">;
  line2?: Flex__<"div">;
  line3?: Flex__<"div">;
  line4?: Flex__<"div">;
  icons5?: Flex__<"div">;
  line5?: Flex__<"div">;
  icons6?: Flex__<"div">;
  line6?: Flex__<"div">;
  icons7?: Flex__<"div">;
  oCard?: Flex__<typeof OCard>;
  textField?: Flex__<typeof TextField>;
  checkboxGroup?: Flex__<typeof CheckboxGroup>;
  option1?: Flex__<typeof Checkbox>;
  option2?: Flex__<typeof Checkbox>;
  option3?: Flex__<typeof Checkbox>;
  _11?: Flex__<"div">;
  rectangle1?: Flex__<"div">;
  _11Completed?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
};

export interface DefaultOnboarding4Props {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicOnboarding4__RenderFunc(props: {
  variants: PlasmicOnboarding4__VariantsArgs;
  args: PlasmicOnboarding4__ArgsType;
  overrides: PlasmicOnboarding4__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textField.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``
      },
      {
        path: "checkboxGroup.value",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "option1.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "option2.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "option3.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_library_plasmic_color_type =
    useStyleTokens_library_plasmic_color_type();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            styleTokensClassNames_library_plasmic_color_type,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__ur0Ew)}>
            <Header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames("__wab_instance", sty.header)}
              onboarding={"unnamedVariant"}
            />
          </div>
          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <div
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__iEbK6)}>
                <div className={classNames(projectcss.all, sty.freeBox__y63Rm)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__o35D)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___6Bk3Y
                      )}
                    >
                      <div
                        data-plasmic-name={"icons3"}
                        data-plasmic-override={overrides.icons3}
                        className={classNames(projectcss.all, sty.icons3)}
                      >
                        <ProggressingAnimationIcon
                          className={classNames(projectcss.all, sty.svg__ddwBo)}
                          role={"img"}
                        />
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__heSsh)}
                    >
                      <div
                        data-plasmic-name={"line1"}
                        data-plasmic-override={overrides.line1}
                        className={classNames(projectcss.all, sty.line1)}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__r0CtA)}
                    >
                      <div
                        data-plasmic-name={"icons8"}
                        data-plasmic-override={overrides.icons8}
                        className={classNames(projectcss.all, sty.icons8)}
                      >
                        <div
                          data-plasmic-name={"icons9"}
                          data-plasmic-override={overrides.icons9}
                          className={classNames(projectcss.all, sty.icons9)}
                        >
                          <TickCircleIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__qoR3
                            )}
                            role={"img"}
                          />
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__nGj9X)}
                    >
                      <div
                        data-plasmic-name={"icons10"}
                        data-plasmic-override={overrides.icons10}
                        className={classNames(projectcss.all, sty.icons10)}
                      >
                        <div
                          data-plasmic-name={"icons11"}
                          data-plasmic-override={overrides.icons11}
                          className={classNames(projectcss.all, sty.icons11)}
                        >
                          <TickCircleIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__f3CcA
                            )}
                            role={"img"}
                          />
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___1B6Sq
                      )}
                    >
                      <div
                        data-plasmic-name={"icons12"}
                        data-plasmic-override={overrides.icons12}
                        className={classNames(projectcss.all, sty.icons12)}
                      >
                        <div
                          data-plasmic-name={"icons13"}
                          data-plasmic-override={overrides.icons13}
                          className={classNames(projectcss.all, sty.icons13)}
                        >
                          <TickCircleIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__fjxp5
                            )}
                            role={"img"}
                          />
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___26Ro3
                      )}
                    >
                      <div
                        data-plasmic-name={"line2"}
                        data-plasmic-override={overrides.line2}
                        className={classNames(projectcss.all, sty.line2)}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__cnZth)}
                    >
                      <div
                        data-plasmic-name={"line3"}
                        data-plasmic-override={overrides.line3}
                        className={classNames(projectcss.all, sty.line3)}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__dGQg2)}
                    >
                      <div
                        data-plasmic-name={"line4"}
                        data-plasmic-override={overrides.line4}
                        className={classNames(projectcss.all, sty.line4)}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__zoCDc)}
                    >
                      <div
                        data-plasmic-name={"icons5"}
                        data-plasmic-override={overrides.icons5}
                        className={classNames(projectcss.all, sty.icons5)}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__mLcLw)}
                    >
                      <div
                        data-plasmic-name={"line5"}
                        data-plasmic-override={overrides.line5}
                        className={classNames(projectcss.all, sty.line5)}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ikmfj)}
                    >
                      <div
                        data-plasmic-name={"icons6"}
                        data-plasmic-override={overrides.icons6}
                        className={classNames(projectcss.all, sty.icons6)}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__vUu6F)}
                    >
                      <div
                        data-plasmic-name={"line6"}
                        data-plasmic-override={overrides.line6}
                        className={classNames(projectcss.all, sty.line6)}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qGdQ)}
                    >
                      <div
                        data-plasmic-name={"icons7"}
                        data-plasmic-override={overrides.icons7}
                        className={classNames(projectcss.all, sty.icons7)}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ls7Il
                      )}
                    >
                      {"wallet"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xx0Oj
                      )}
                    >
                      {"domain"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cOaUh
                      )}
                    >
                      {"pricing"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bxa06
                      )}
                    >
                      {"mint"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xSqb
                      )}
                    >
                      {"deploy"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zxW3N
                      )}
                    >
                      {"test"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fXpuw
                      )}
                    >
                      {"success"}
                    </div>
                  </div>
                  <OCard
                    data-plasmic-name={"oCard"}
                    data-plasmic-override={overrides.oCard}
                    className={classNames("__wab_instance", sty.oCard)}
                    slot={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2Xiuy
                        )}
                      >
                        {"license creation"}
                      </div>
                    }
                  >
                    <TextField
                      data-plasmic-name={"textField"}
                      data-plasmic-override={overrides.textField}
                      className={classNames("__wab_instance", sty.textField)}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xIbjS
                          )}
                        >
                          {"price-per-crawl"}
                        </div>
                      }
                      onChange={async (...eventArgs: any) => {
                        generateStateOnChangeProp($state, [
                          "textField",
                          "value"
                        ]).apply(null, eventArgs);

                        if (
                          eventArgs.length > 1 &&
                          eventArgs[1] &&
                          eventArgs[1]._plasmic_state_init_
                        ) {
                          return;
                        }
                      }}
                      placeholder={"$0.01"}
                      value={generateStateValueProp($state, [
                        "textField",
                        "value"
                      ])}
                    />

                    <CheckboxGroup
                      data-plasmic-name={"checkboxGroup"}
                      data-plasmic-override={overrides.checkboxGroup}
                      className={classNames(
                        "__wab_instance",
                        sty.checkboxGroup
                      )}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__elWsc
                          )}
                        >
                          {"terms"}
                        </div>
                      }
                      onChange={async (...eventArgs: any) => {
                        generateStateOnChangeProp($state, [
                          "checkboxGroup",
                          "value"
                        ]).apply(null, eventArgs);

                        if (
                          eventArgs.length > 1 &&
                          eventArgs[1] &&
                          eventArgs[1]._plasmic_state_init_
                        ) {
                          return;
                        }
                      }}
                      options={
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___6Rkt
                          )}
                        >
                          <Checkbox
                            data-plasmic-name={"option1"}
                            data-plasmic-override={overrides.option1}
                            className={classNames(
                              "__wab_instance",
                              sty.option1
                            )}
                            isSelected={generateStateValueProp($state, [
                              "option1",
                              "isSelected"
                            ])}
                            label={
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__i0Xmu
                                )}
                              >
                                {"allow ai training"}
                              </div>
                            }
                            onChange={async (...eventArgs: any) => {
                              generateStateOnChangeProp($state, [
                                "option1",
                                "isSelected"
                              ]).apply(null, eventArgs);

                              if (
                                eventArgs.length > 1 &&
                                eventArgs[1] &&
                                eventArgs[1]._plasmic_state_init_
                              ) {
                                return;
                              }
                            }}
                            value={"option1"}
                          />

                          <Checkbox
                            data-plasmic-name={"option2"}
                            data-plasmic-override={overrides.option2}
                            className={classNames(
                              "__wab_instance",
                              sty.option2
                            )}
                            isSelected={generateStateValueProp($state, [
                              "option2",
                              "isSelected"
                            ])}
                            label={
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___2Ww8U
                                )}
                              >
                                {"allow commercial use"}
                              </div>
                            }
                            onChange={async (...eventArgs: any) => {
                              generateStateOnChangeProp($state, [
                                "option2",
                                "isSelected"
                              ]).apply(null, eventArgs);

                              if (
                                eventArgs.length > 1 &&
                                eventArgs[1] &&
                                eventArgs[1]._plasmic_state_init_
                              ) {
                                return;
                              }
                            }}
                            value={"option2"}
                          />

                          <Checkbox
                            data-plasmic-name={"option3"}
                            data-plasmic-override={overrides.option3}
                            className={classNames(
                              "__wab_instance",
                              sty.option3
                            )}
                            isSelected={generateStateValueProp($state, [
                              "option3",
                              "isSelected"
                            ])}
                            label={
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___3JKNf
                                )}
                              >
                                {"require attribution"}
                              </div>
                            }
                            onChange={async (...eventArgs: any) => {
                              generateStateOnChangeProp($state, [
                                "option3",
                                "isSelected"
                              ]).apply(null, eventArgs);

                              if (
                                eventArgs.length > 1 &&
                                eventArgs[1] &&
                                eventArgs[1]._plasmic_state_init_
                              ) {
                                return;
                              }
                            }}
                            value={"option3"}
                          />
                        </div>
                      }
                      value={generateStateValueProp($state, [
                        "checkboxGroup",
                        "value"
                      ])}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__b9RbE)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__hG9H
                        )}
                        color={"outlineBlue"}
                        size={"compact"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__lpl2L
                          )}
                        >
                          {"custom terms"}
                        </div>
                      </Button>
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__wf5Tk
                        )}
                        color={"outlineBlue"}
                        size={"compact"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___311X1
                          )}
                        >
                          {"preview license"}
                        </div>
                      </Button>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__taaVd)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__pEsgB
                        )}
                        color={"tachi6"}
                      >
                        {"mint nft"}
                      </Button>
                      <div
                        data-plasmic-name={"_11"}
                        data-plasmic-override={overrides._11}
                        className={classNames(projectcss.all, sty._11)}
                      >
                        <div
                          data-plasmic-name={"rectangle1"}
                          data-plasmic-override={overrides.rectangle1}
                          className={classNames(projectcss.all, sty.rectangle1)}
                        />

                        <div
                          data-plasmic-name={"_11Completed"}
                          data-plasmic-override={overrides._11Completed}
                          className={classNames(
                            projectcss.all,
                            sty._11Completed
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___33WYt
                            )}
                          >
                            {"0.0013 eth gas fee"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </OCard>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___0LkEl)}
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__fdx8N)}
                    color={"outlineBlue"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vn2Bo
                      )}
                    >
                      {"back"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__hBcld)}
                    color={"tachi6"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__a5L37
                      )}
                    >
                      {"continue"}
                    </div>
                  </Button>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__uzXpq)}>
                <PlasmicImg__
                  data-plasmic-name={"img"}
                  data-plasmic-override={overrides.img}
                  alt={""}
                  className={classNames(sty.img)}
                  displayHeight={"550px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tachi_landing_page/images/tachiPitchDeck22Png2.png",
                    fullWidth: 4800,
                    fullHeight: 2700,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "section",
    "columns",
    "icons3",
    "line1",
    "icons8",
    "icons9",
    "icons10",
    "icons11",
    "icons12",
    "icons13",
    "line2",
    "line3",
    "line4",
    "icons5",
    "line5",
    "icons6",
    "line6",
    "icons7",
    "oCard",
    "textField",
    "checkboxGroup",
    "option1",
    "option2",
    "option3",
    "_11",
    "rectangle1",
    "_11Completed",
    "img"
  ],
  header: ["header"],
  section: [
    "section",
    "columns",
    "icons3",
    "line1",
    "icons8",
    "icons9",
    "icons10",
    "icons11",
    "icons12",
    "icons13",
    "line2",
    "line3",
    "line4",
    "icons5",
    "line5",
    "icons6",
    "line6",
    "icons7",
    "oCard",
    "textField",
    "checkboxGroup",
    "option1",
    "option2",
    "option3",
    "_11",
    "rectangle1",
    "_11Completed",
    "img"
  ],
  columns: [
    "columns",
    "icons3",
    "line1",
    "icons8",
    "icons9",
    "icons10",
    "icons11",
    "icons12",
    "icons13",
    "line2",
    "line3",
    "line4",
    "icons5",
    "line5",
    "icons6",
    "line6",
    "icons7",
    "oCard",
    "textField",
    "checkboxGroup",
    "option1",
    "option2",
    "option3",
    "_11",
    "rectangle1",
    "_11Completed",
    "img"
  ],
  icons3: ["icons3"],
  line1: ["line1"],
  icons8: ["icons8", "icons9"],
  icons9: ["icons9"],
  icons10: ["icons10", "icons11"],
  icons11: ["icons11"],
  icons12: ["icons12", "icons13"],
  icons13: ["icons13"],
  line2: ["line2"],
  line3: ["line3"],
  line4: ["line4"],
  icons5: ["icons5"],
  line5: ["line5"],
  icons6: ["icons6"],
  line6: ["line6"],
  icons7: ["icons7"],
  oCard: [
    "oCard",
    "textField",
    "checkboxGroup",
    "option1",
    "option2",
    "option3",
    "_11",
    "rectangle1",
    "_11Completed"
  ],
  textField: ["textField"],
  checkboxGroup: ["checkboxGroup", "option1", "option2", "option3"],
  option1: ["option1"],
  option2: ["option2"],
  option3: ["option3"],
  _11: ["_11", "rectangle1", "_11Completed"],
  rectangle1: ["rectangle1"],
  _11Completed: ["_11Completed"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  section: "section";
  columns: "div";
  icons3: "div";
  line1: "div";
  icons8: "div";
  icons9: "div";
  icons10: "div";
  icons11: "div";
  icons12: "div";
  icons13: "div";
  line2: "div";
  line3: "div";
  line4: "div";
  icons5: "div";
  line5: "div";
  icons6: "div";
  line6: "div";
  icons7: "div";
  oCard: typeof OCard;
  textField: typeof TextField;
  checkboxGroup: typeof CheckboxGroup;
  option1: typeof Checkbox;
  option2: typeof Checkbox;
  option3: typeof Checkbox;
  _11: "div";
  rectangle1: "div";
  _11Completed: "div";
  img: typeof PlasmicImg__;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicOnboarding4__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicOnboarding4__VariantsArgs;
    args?: PlasmicOnboarding4__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicOnboarding4__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicOnboarding4__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicOnboarding4__ArgProps,
          internalVariantPropNames: PlasmicOnboarding4__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicOnboarding4__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOnboarding4";
  } else {
    func.displayName = `PlasmicOnboarding4.${nodeName}`;
  }
  return func;
}

export const PlasmicOnboarding4 = Object.assign(
  // Top-level PlasmicOnboarding4 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    section: makeNodeComponent("section"),
    columns: makeNodeComponent("columns"),
    icons3: makeNodeComponent("icons3"),
    line1: makeNodeComponent("line1"),
    icons8: makeNodeComponent("icons8"),
    icons9: makeNodeComponent("icons9"),
    icons10: makeNodeComponent("icons10"),
    icons11: makeNodeComponent("icons11"),
    icons12: makeNodeComponent("icons12"),
    icons13: makeNodeComponent("icons13"),
    line2: makeNodeComponent("line2"),
    line3: makeNodeComponent("line3"),
    line4: makeNodeComponent("line4"),
    icons5: makeNodeComponent("icons5"),
    line5: makeNodeComponent("line5"),
    icons6: makeNodeComponent("icons6"),
    line6: makeNodeComponent("line6"),
    icons7: makeNodeComponent("icons7"),
    oCard: makeNodeComponent("oCard"),
    textField: makeNodeComponent("textField"),
    checkboxGroup: makeNodeComponent("checkboxGroup"),
    option1: makeNodeComponent("option1"),
    option2: makeNodeComponent("option2"),
    option3: makeNodeComponent("option3"),
    _11: makeNodeComponent("_11"),
    rectangle1: makeNodeComponent("rectangle1"),
    _11Completed: makeNodeComponent("_11Completed"),
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicOnboarding4
    internalVariantProps: PlasmicOnboarding4__VariantProps,
    internalArgProps: PlasmicOnboarding4__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicOnboarding4;
/* prettier-ignore-end */
