
name = "tachi-e2e-test"
main = "dist/index.js"
compatibility_date = "2024-01-01"

[env.production]
vars = { 
  BASE_RPC_URL = "https://sepolia.base.org",
  PAYMENT_PROCESSOR_ADDRESS = "0xBbe8D73B6B44652A5Fb20678bFa27b785Bb7Df41",
  PROOF_OF_CRAWL_LEDGER_ADDRESS = "0xA20e592e294FEbb5ABc758308b15FED437AB1EF9",
  USDC_ADDRESS = "0x036CbD53842c5426634e7929541eC2318f3dCF7e",
  CRAWL_TOKEN_ID = "1",
  PRICE_USDC = "0.01",
  PUBLISHER_ADDRESS = "0xdDa104A3EcA774039aE2800f53dAbA4da8C8306d"
}
