/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: enk3K4vZ6pmH6kVCoZJXGn

import {
  createStyleTokensProvider,
  createUseStyleTokens
} from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: enk3K4vZ6pmH6kVCoZJXGn/projectModule

import * as projectcss from "./plasmic.module.css"; // plasmic-import: enk3K4vZ6pmH6kVCoZJXGn/projectcss

const data = {
  base: projectcss.plasmic_tokens,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);

export const StyleTokensProvider = createStyleTokensProvider(
  data,
  _useGlobalVariants
);
