# Tachi Protocol - Multi-Environment Configuration
# ==================================================

# Default Development Environment
# This configuration is used for local development and testing
name = "tachi-gateway-dev"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Development routes (localhost testing)
# No routes defined for development - uses wrangler dev

[vars]
ENVIRONMENT = "development"
# Development uses Base Sepolia testnet
BASE_RPC_URL = "https://base-sepolia.g.alchemy.com/v2/your-dev-api-key"
CONTRACT_ADDRESS = "0x5a9c9Aa7feC1DF9f5702BcCEB21492be293E5d5F"  # Dev contract
USDC_ADDRESS = "0x036CbD53842c5426634e7929541eC2318f3dCF7e"        # Base Sepolia USDC
PRICE_USDC = "0.001"
PAYMENT_PROCESSOR_ADDRESS = "0x5a9c9Aa7feC1DF9f5702BcCEB21492be293E5d5F"
PROOF_OF_CRAWL_LEDGER_ADDRESS = "0xeC3311cCd41B450a12404E7D14165D0dfa0725c3"
CRAWL_TOKEN_ID = "1"
PUBLISHER_ADDRESS = "0x1C5a9A0228efc875484Bca44df3987bB6A2aca23"
SENTRY_DSN = "https://your-dev-sentry-dsn@o123456789.ingest.sentry.io/123456789"
BETTER_UPTIME_HEARTBEAT_URL = "https://betteruptime.com/api/v1/heartbeat/dev-heartbeat-token"
# Enable debug logging in development
DEBUG_MODE = "true"
LOG_LEVEL = "debug"

# Development KV namespaces (if using KV storage)
[[kv_namespaces]]
binding = "TACHI_CACHE"
id = "your-dev-kv-namespace-id"
preview_id = "your-dev-kv-preview-id"

# Rate Limiting binding
[[rate_limiting]]
binding = "RATE_LIMITER"

# ==============================================
# STAGING ENVIRONMENT
# ==============================================
[env.staging]
name = "tachi-gateway-staging"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Staging routes - subdomain routing
routes = [
  { pattern = "staging.mydapp.com/*", zone_name = "mydapp.com" }
]

[env.staging.vars]
ENVIRONMENT = "staging"
# Staging can use testnet or mainnet depending on your testing strategy
BASE_RPC_URL = "https://base-sepolia.g.alchemy.com/v2/your-staging-api-key"
CONTRACT_ADDRESS = "0x8b3192f5EeBd6c427C3EA0B8EC2cFf31b98C4F80"  # Staging contract
USDC_ADDRESS = "0x036CbD53842c5426634e7929541eC2318f3dCF7e"        # Base Sepolia USDC
PRICE_USDC = "0.001"
PAYMENT_PROCESSOR_ADDRESS = "0x8b3192f5EeBd6c427C3EA0B8EC2cFf31b98C4F80"
PROOF_OF_CRAWL_LEDGER_ADDRESS = "0x9c4283a462F5eEb3C3Fa0B9EC3fF41c41b78D4C90"
CRAWL_TOKEN_ID = "1"
PUBLISHER_ADDRESS = "0x2C6b9A0338efc975594BdA55ee4987cB7A3aca34"
SENTRY_DSN = "https://your-staging-sentry-dsn@o123456789.ingest.sentry.io/987654321"
BETTER_UPTIME_HEARTBEAT_URL = "https://betteruptime.com/api/v1/heartbeat/staging-heartbeat-token"
# Moderate logging in staging
DEBUG_MODE = "false"
LOG_LEVEL = "info"

# Staging KV namespaces
[[env.staging.kv_namespaces]]
binding = "TACHI_CACHE"
id = "your-staging-kv-namespace-id"

# ==============================================
# PRODUCTION ENVIRONMENT
# ==============================================
[env.production]
name = "tachi-gateway-production"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Production routes - wildcard for main domain and subdomains
routes = [
  { pattern = "*.mydapp.com/*", zone_name = "mydapp.com" },
  { pattern = "mydapp.com/*", zone_name = "mydapp.com" }
]

[env.production.vars]
ENVIRONMENT = "production"
# Production uses Base mainnet
BASE_RPC_URL = "https://base-mainnet.g.alchemy.com/v2/your-production-api-key"
CONTRACT_ADDRESS = "0xa974E189038f5b0dEcEbfCe7B0A108824acF3813"  # Production contract
USDC_ADDRESS = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"        # Base mainnet USDC
PRICE_USDC = "0.001"
PAYMENT_PROCESSOR_ADDRESS = "0xa974E189038f5b0dEcEbfCe7B0A108824acF3813"
PROOF_OF_CRAWL_LEDGER_ADDRESS = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
CRAWL_TOKEN_ID = "1"
PUBLISHER_ADDRESS = "0x3D7b9A0449efc875594CdA66ff5987dB8A4aca45"
SENTRY_DSN = "https://your-production-sentry-dsn@o123456789.ingest.sentry.io/456789123"
BETTER_UPTIME_HEARTBEAT_URL = "https://betteruptime.com/api/v1/heartbeat/production-heartbeat-token"
# Minimal logging in production for performance
DEBUG_MODE = "false"
LOG_LEVEL = "error"

# Production KV namespaces
[[env.production.kv_namespaces]]
binding = "TACHI_CACHE"
id = "your-production-kv-namespace-id"

# ==============================================
# SECRETS CONFIGURATION
# ==============================================
# Secrets are set per environment using wrangler secret put commands:
# 
# Development:
# wrangler secret put PRIVATE_KEY --env development
# wrangler secret put ALCHEMY_API_KEY --env development
# 
# Staging:
# wrangler secret put PRIVATE_KEY --env staging
# wrangler secret put ALCHEMY_API_KEY --env staging
# 
# Production:
# wrangler secret put PRIVATE_KEY --env production
# wrangler secret put ALCHEMY_API_KEY --env production
#
# Common secrets needed:
# - PRIVATE_KEY: Ethereum private key for transaction signing
# - ALCHEMY_API_KEY: Alchemy API key for RPC access
# - SENTRY_AUTH_TOKEN: Sentry authentication token
# - DATABASE_URL: Database connection string (if using D1 or external DB)

# ==============================================
# DEPLOYMENT COMMANDS
# ==============================================
# 
# Deploy to staging:
# npx wrangler deploy --env staging
# 
# Deploy to production:
# npx wrangler deploy --env production
# 
# Local development:
# npx wrangler dev
# 
# Local development with staging config:
# npx wrangler dev --env staging
#
