[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
fs_permissions = [{access = "read-write", path = "./deployments"}]
# Load environment variables from root .env file
env_file = "../.env"

[profile.default.fmt]
line_length = 100
tab_width = 2
bracket_spacing = false

[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base = {key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api"}
base_sepolia = {key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api"}
